"""
    LegacyXfoil <: Method

In general usage, this struct is generated by calling the LegacyXfoil constructor.

# Fields
- `reynolds`: Reynolds number. If `nothing`, an inviscid analysis is run.
- `mach`: Mach number
- `xtrip`: forced transition x/c locations on top/bottom sides
- `reinit`: reinitialize the solution? (rather than use the previous solution)
- `iter`: Maximum iterations for viscous analyses
- `npan`: Number of panels
- `percussive_maintenance`: Call `do_percussive_maintenance` upon
   convergence failure?
- `printdata`: Print data obtained from XFOIL during the solution?
- `zeroinit`: Start angle of attack sweeps from zero?  If `true`, results will be sorted by ascending angle of attack.
- `clmaxstop`: Stop if lift coefficient decreases twice consecutively going up?
- `clminstop`: Stop if lift coefficient increases twice consecutively going down?
"""
struct LegacyXfoil{Tre,Tma,Txt,Tri,Tit,Tnp,Tpm,Tpd,Tzi,Tcmx,Tcmn} <: Method
    reynolds::Tre
    mach::Tma
    xtrip::Txt
    reinit::Tri
    iter::Tit
    npan::Tnp
    percussive_maintenance::Tpm
    printdata::Tpd
    zeroinit::Tzi
    clmaxstop::Tcmx
    clminstop::Tcmn
end

"""
    LegacyXfoil(;
        reynolds=nothing,
        mach=0.0,
        xtrip=(1.0, 1.0),
        reinit=false,
        iter=50,
        npan=140,
        percussive_maintenance=!reinit,
        printdata=false,
        zeroinit=true,
        clmaxstop=false,
        clminstop=false,
    )

Constructor for LegacyXfoil type. Pass `reynolds=nothing` (the default) for an inviscid
analysis; pass a numeric Reynolds number for a viscous analysis.

# Keyword Arguments
- `reynolds=nothing` : Reynolds number. `nothing` selects the inviscid Xfoil.jl path.
- `mach::Float=0.0` : Mach number
- `xtrip::Tuple{Float, Float}=(1.0,1.0)`: forced transition x/c locations on top/bottom sides
- `reinit::Bool=false`: reinitialize the solution? (rather than use the previous solution)
- `iter::Int=50`: Maximum iterations for viscous analyses
- `npan::Int=140`: Number of panels
- `percussive_maintenance::Bool=!reinit`: Call `do_percussive_maintenance` upon convergence failure?
- `printdata::Bool=false`: Print data obtained from XFOIL during the solution?
- `zeroinit::Bool=true`: Start angle of attack sweeps from zero?  If `true`, results will be sorted by ascending angle of attack.
- `clmaxstop::Bool=false`: Stop if lift coefficient decreases twice consecutively going up?
- `clminstop::Bool=false`: Stop if lift coefficient increases twice consecutively going down?

# Returns
- `method::LegacyXfoil` : LegacyXfoil method object
"""
function LegacyXfoil(;
    reynolds=nothing,
    mach=0.0,
    xtrip=(1.0, 1.0),
    reinit=false,
    iter=50,
    npan=140,
    percussive_maintenance=!reinit,
    printdata=false,
    zeroinit=true,
    clmaxstop=false,
    clminstop=false,
)
    return LegacyXfoil(
        reynolds,
        mach,
        xtrip,
        reinit,
        iter,
        npan,
        percussive_maintenance,
        printdata,
        zeroinit,
        clmaxstop,
        clminstop,
    )
end

"""
    LegacyXFOutputs

# Fields
- `cl::Vector{Float}` : lift coefficient per angle of attack
- `cd::Vector{Float}` : drag coefficient per angle of attack (zeros for inviscid)
- `cdp::Vector{Float}` : pressure-drag coefficient per angle of attack (zeros for inviscid)
- `cm::Vector{Float}` : moment coefficient per angle of attack
- `converged::Vector{Bool}` : convergence flag per angle of attack
- `x_cp` : x/c locations for the surface cp distribution. Populated only when a single
  angle of attack is requested; `nothing` for multi-α sweeps.
- `cp` : surface pressure coefficient at `x_cp`. Populated only for single-α calls.
- `bl` : NamedTuple `(s, x, y, ue, dstar, theta, cf)` from Xfoil.jl's `bldump()`.
  Populated only for single-α viscous calls; `nothing` for inviscid or multi-α calls.
"""
@kwdef struct LegacyXFOutputs{Tcl,Tcd,Tcdp,Tcm,Tconv,Txcp,Tcp,Tbl}
    cl::Tcl
    cd::Tcd
    cdp::Tcdp
    cm::Tcm
    converged::Tconv
    x_cp::Txcp = nothing
    cp::Tcp = nothing
    bl::Tbl = nothing
end

"""
    analyze_lxf(coordinates, flow_angles; method=LegacyXfoil())

Analysis function for LegacyXfoil.

# Arguments
- `coordinates::Matrix{Float}` : [x y] coordinates
- `alpha::AbstractVector` : angles of attack at which to analyze (degrees)

# Keyword Arguments
- `method::LegacyXfoil` : A LegacyXfoil method object.

# Returns
- `outputs::LegacyXFOutputs` : outputs object (see [`LegacyXFOutputs`](@ref) for fields).
  For single-α calls, `cp`/`x_cp` are populated and `bl` is populated when viscous.
"""
function analyze_lxf(coordinates, alpha; method=LegacyXfoil())

    x_rev = reverse(coordinates[:, 1])
    y_rev = reverse(coordinates[:, 2])

    naoa = length(alpha)

    # Branch viscous vs inviscid. For single-α we force zeroinit=false so that the
    # internal Xfoil state left over after the sweep corresponds to the user's α
    # (otherwise zeroinit interleaves an α=0 solve and cpdump/bldump would return
    # state from the wrong angle).
    single = naoa == 1
    zeroinit_eff = single ? false : method.zeroinit

    if method.reynolds === nothing
        # Inviscid path: 3-arg alpha_sweep returns (cl, cm) only.
        cl, cm = xf.alpha_sweep(
            x_rev,
            y_rev,
            alpha;
            method.mach,
            method.npan,
            method.printdata,
            zeroinit=zeroinit_eff,
        )
        cd = zeros(eltype(cl), naoa)
        cdp = zeros(eltype(cl), naoa)
        converged = trues(naoa)
    else
        cl, cd, cdp, cm, converged = xf.alpha_sweep(
            x_rev,
            y_rev,
            alpha,
            method.reynolds;
            method.mach,
            method.xtrip,
            method.reinit,
            method.iter,
            method.npan,
            method.percussive_maintenance,
            method.printdata,
            zeroinit=zeroinit_eff,
            method.clmaxstop,
            method.clminstop,
        )
    end

    if single
        x_cp, cp = xf.cpdump()
        bl = if method.reynolds === nothing
            nothing
        else
            s, x_bl, y_bl, ue, dstar, theta, cf = xf.bldump()
            (; s, x=x_bl, y=y_bl, ue, dstar, theta, cf)
        end
        return LegacyXFOutputs(;
            cl, cd, cdp, cm, converged, x_cp, cp, bl
        )
    else
        return LegacyXFOutputs(; cl, cd, cdp, cm, converged)
    end
end
